### PR TITLE
Modified aws-rds-status and aws-sqs-status to default to IAM profile …

### PR DESCRIPTION
**Pull request by gorandev**
…is access and secret are absent.

### CODE REVIEW

**Comment by jamtur01** [comment]
Is this true of the other tools in the AWS suite too? Should they be updated?

**Comment by gorandev** [comment]
I think Fog::AWS supports IAM for all the services. Would you like me to extend this PR and modify all others tools too?

**Comment by jamtur01** [comment]
That'd be great! It'd be good to have them all consistent.

**Comment by gorandev** [comment]
Ok that's all of them!

**Comment by jamtur01** [comment]
Thanks!

**Pull request merged**
