### PR TITLE
Bump version to 1.2.0

### PR DESCRIPTION
**Pull request by smortex**
While here, fix how gem tags are formatted by the Ruby ecosystem.

### CODE REVIEW

**Comment by jamtur01** [comment]
It's been a while since I did much with gems? Is the `v` prefix preferred?

**Comment by smortex** [comment]
@jamtur01 when you `rake release` it's the way tag is named by the `bundler/gem_tasks` tasks.  Seems to be some kind of standard, I prefer the tag to be the version but some people seem to not like that :smile:

**Comment by smortex** [comment]
This change is only related to github-changelog-generator: this allows it to build the correct URL.

**Comment by jamtur01** [comment]
Who are we to deny the people? :)

**Comment by smortex** [comment]
@jamtur01 are you OK for this new release?

**Review by jamtur01 — APPROVED** [review]
LGTM

**Pull request merged**
